"""empty message

Revision ID: 081e11087125
Revises: 63012e6907fe
Create Date: 2022-05-04 17:43:51.679926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '081e11087125'
down_revision = '63012e6907fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(), nullable=True))
    op.drop_column('user', 'avatar_data')
    op.drop_column('user', 'avatar_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('avatar_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
