"""empty message

Revision ID: 10f3cda0c765
Revises: ee8816649afe
Create Date: 2022-03-28 17:05:02.070288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f3cda0c765'
down_revision = 'ee8816649afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('cardDescription', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'cardDescription')
    # ### end Alembic commands ###
