"""empty message

Revision ID: 2fc47db59231
Revises: c0cfbe3ea8c1
Create Date: 2022-03-23 18:18:11.296734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc47db59231'
down_revision = 'c0cfbe3ea8c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('student')
    op.drop_table('teacher')
    op.drop_constraint('payment_subject_id_fkey', 'payment', type_='foreignkey')
    op.drop_column('payment', 'subject_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('payment_subject_id_fkey', 'payment', 'subject', ['subject_id'], ['id'])
    op.create_table('teacher',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='teacher_subject_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='teacher_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teacher_pkey')
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='student_payment_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='student_subject_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='student_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='student_pkey')
    )
    op.drop_table('payment_detail')
    op.drop_table('active_user')
    # ### end Alembic commands ###
