"""empty message

Revision ID: 30901d1078c1
Revises: cebc03efa99e
Create Date: 2022-05-05 16:19:56.766765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30901d1078c1'
down_revision = 'cebc03efa99e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_data')
    # ### end Alembic commands ###
