"""empty message

Revision ID: 407fe66217f9
Revises: 6533c8d770c8
Create Date: 2022-04-08 19:00:53.096191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407fe66217f9'
down_revision = '6533c8d770c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payment', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'stripe_id')
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'stripe_subscription_id')
    # ### end Alembic commands ###
