"""empty message

Revision ID: 5b4d24e4fb2e
Revises: 746780fd8dee
Create Date: 2022-04-08 17:20:37.245043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6533c8d770c8'
down_revision = '746780fd8dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=155), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=70),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_table('invitation_code')
    # ### end Alembic commands ###
