"""empty message

Revision ID: 71c2878d34f8
Revises: 5b4d24e4fb2e
Create Date: 2022-04-22 19:12:04.752619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c2878d34f8'
down_revision = '5b4d24e4fb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['stripe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'stripe_id')
    # ### end Alembic commands ###
