"""empty message

Revision ID: 746780fd8dee
Revises: 232ee97f591b
Create Date: 2022-04-07 16:11:18.462336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746780fd8dee'
down_revision = "10f3cda0c765"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('stripe_subscription_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'payment', ['stripe_subscription_id'])
    op.drop_constraint('subject_stripe_id_key', 'subject', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('subject_stripe_id_key', 'subject', ['stripe_id'])
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'stripe_subscription_id')
    # ### end Alembic commands ###
