"""empty message

Revision ID: 76dd04bd09bb
Revises: 2fc47db59231
Create Date: 2022-03-23 18:35:23.043635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76dd04bd09bb'
down_revision = '2fc47db59231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('payment_id', 'subject_id')
    )
    op.drop_table('payment_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_detail',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='payment_detail_payment_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='payment_detail_subject_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_detail_pkey')
    )
    op.drop_table('tags')
    # ### end Alembic commands ###
