"""empty message

Revision ID: cebc03efa99e
Revises: 081e11087125
Create Date: 2022-05-05 16:17:03.536323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cebc03efa99e'
down_revision = '081e11087125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('avatar_mime', sa.String(), nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar_mime')
    op.drop_column('user', 'avatar_name')
    # ### end Alembic commands ###
