"""empty message

Revision ID: ee8816649afe
Revises: 33e9074f743d
Create Date: 2022-03-25 19:19:22.385599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8816649afe'
down_revision = '33e9074f743d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userSubjects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'subject_id')
    )
    op.drop_table('userSubkects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userSubkects',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name='userSubkects_subject_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='userSubkects_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'subject_id', name='userSubkects_pkey')
    )
    op.drop_table('userSubjects')
    # ### end Alembic commands ###
